{
  "Competitive Programming Template": {
    "prefix": "cpp",
    "body": [
      "/**",
      " * All Praise to Allah",
      " * ---------------------",
      " * Author: Al Kayes Rifat",
      " * Portfolio  : alkayesrifat.netlify.app",
      " * Date       : ${CURRENT_DATE}/${CURRENT_MONTH}/${CURRENT_YEAR} (${CURRENT_DAY_NAME})",
      " * Time       : ${CURRENT_HOUR}:${CURRENT_MINUTE} ",
      " * ---------------------",
      " */",
      "",
      "#include<bits/stdc++.h>",
      "#include<ext/pb_ds/assoc_container.hpp>",
      "#include<ext/pb_ds/tree_policy.hpp>",
      "using namespace __gnu_pbds;",
      "using namespace std;",
      "template <typename T> using pbds = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;// - Use 'less<T>' for set, 'less_equal<T>' for multiset",
      "#define ll long long int",
      "#define ull unsigned long long",
      "#define endl \"\\n\"",
      "",
      "int main(){",
      "",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "",
      "    $0",
      "",
      "    return 0;",
      "}"
    ],
    "description": "Basic template for competitive programming in C++"
  },
  "Test Case Competitive Programming": {
    "prefix": "testcpp",
    "body": [
      "/**",
      " * All Praise to Allah",
      " * ---------------------",
      " * Author: Al Kayes Rifat",
      " * Portfolio  : alkayesrifat.netlify.app",
      " * Date       : ${CURRENT_DATE}/${CURRENT_MONTH}/${CURRENT_YEAR} (${CURRENT_DAY_NAME})",
      " * Time       : ${CURRENT_HOUR}:${CURRENT_MINUTE} ",
      " * ---------------------",
      " */",
      "",
      "#include<bits/stdc++.h>",
      "#include<ext/pb_ds/assoc_container.hpp>",
      "#include<ext/pb_ds/tree_policy.hpp>",
      "using namespace __gnu_pbds;",
      "using namespace std;",
      "template <typename T> using pbds = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;// - Use 'less<T>' for set, 'less_equal<T>' for multiset",
      "#define ll long long int",
      "#define ull unsigned long long",
      "#define endl \"\\n\"",
      "",
      "int main(){",
      "",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "",
      
      "    int test_case ;",
      "    cin >>  test_case ;",
      "    while(test_case--)",
      "    {",
      "        $0",
      "",
      "    }",
      "",
      "    return 0;",
      "}"
    ],
    "description": "Basic template for competitive programming in C++"
  }
}
