{
  "Competitive Programming Template": {
    "prefix": "cpp",
    "body": [
      "/**",
      " * All Praise to Allah",
      " * ---------------------",
      " * Author: Al Kayes Rifat",
      " * Portfolio  : alkayesrifat.netlify.app",
      " * Date       : ${CURRENT_DATE}/${CURRENT_MONTH}/${CURRENT_YEAR} (${CURRENT_DAY_NAME})",
      " * Time       : ${CURRENT_HOUR}:${CURRENT_MINUTE} ",
      " * ---------------------",
      " */",
      "",
      "#include<bits/stdc++.h>",
      "using namespace std;",
      "#define ll long long int",
      "#define no cout << \"NO\" <<\"\\n\"",
      "#define yes cout << \"YES\" <<\"\\n\"",
      "#define endl \"\\n\"",
      "",
      "int main(){",
      "",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "",
      "    $0",
      "",
      "    return 0;",
      "}"
    ],
    "description": "Basic template for competitive programming in C++"
  },
  "Test Case Competitive Programming": {
    "prefix": "testcpp",
    "body": [
      "/**",
      " * All Praise to Allah",
      " * ---------------------",
      " * Author: Al Kayes Rifat",
      " * Portfolio  : alkayesrifat.netlify.app",
      " * Date       : ${CURRENT_DATE}/${CURRENT_MONTH}/${CURRENT_YEAR} (${CURRENT_DAY_NAME})",
      " * Time       : ${CURRENT_HOUR}:${CURRENT_MINUTE} ",
      " * ---------------------",
      " */",
      "",
      "#include<bits/stdc++.h>",
      "using namespace std;",
      "#define ll long long int",
      "#define no cout << \"NO\" <<\"\\n\"",
      "#define yes cout << \"YES\" <<\"\\n\"",
      "#define endl \"\\n\"",
      "",
      "int main(){",
      "",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "",
      
      "    int test_case ;",
      "    cin >>  test_case ;",
      "    while(test_case--) ;",
      "    {",
      "        $0",
      "",
      "    }",
      "",
      "    return 0;",
      "}"
    ],
    "description": "Basic template for competitive programming in C++"
  }
}
